# Numpy

Most powerful numerical processing library in python. Array Oriented computing.

Provides extension package to python for multi dimensional array

Very efficient.

Scientific computation

In [ ]:
!pip install numpy

In [3]:
import numpy as np


In [4]:
arr=np.array([2,7,4,8])
print(arr)
print(type(arr))

[2 7 4 8]
<class 'numpy.ndarray'>


In [5]:
arr=np.arange(10)
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


Advantage of Numpy Array over List 

In [6]:
%%time
l=list(range(10000000))
for i in range(10000000):
    l[i]*=l[i]

CPU times: total: 6.08 s
Wall time: 6.38 s


In [7]:
%%time
arr=np.arange(10000000)
arr*=arr

CPU times: total: 62.5 ms
Wall time: 122 ms


## Creating numpy array

In [8]:
arr=np.array([1,2,3,4])
print(arr)
print(arr.ndim)#array dimension
print(arr.shape)#array shape
print(len(arr))
print(arr.dtype)#array item data type
print(arr.itemsize)#array item size

[1 2 3 4]
1
(4,)
4
int32
4


In [9]:
arr=np.array([[1,2,3],[5,6,7]])
print(arr)
print(arr.ndim)#array dimension
print(arr.shape)#array shape
print(len(arr))
print(arr.dtype)#array item data type
print(arr.itemsize)#array item size
print(np.diag(arr)) #return the diagonal elements

[[1 2 3]
 [5 6 7]]
2
(2, 3)
2
int32
4
[1 6]


In [10]:
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr=np.eye(3) #identity Matrix
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr=np.eye(5,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr=np.arange(2,11)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr=np.arange(2,11,2) #arange(start,end, incement/decrement)
arr

array([ 2,  4,  6,  8, 10])

In [16]:
arr=np.random.random((5,2))#get any num b/w 0-1 not inclusive  in 5X2 matrix
arr

array([[0.64779177, 0.14474085],
       [0.80834731, 0.0367874 ],
       [0.90580094, 0.61896762],
       [0.31177384, 0.53036289],
       [0.33732058, 0.75304971]])

In [17]:
arr=np.random.randint(1,10,20)# b/w 1-9 inclusive get 20 vals
arr

array([5, 7, 7, 5, 6, 3, 2, 3, 7, 4, 8, 2, 1, 8, 9, 4, 4, 7, 5, 8])

# NUmpy Indexing

In [18]:
arr= 3 * np.arange(10)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [19]:
arr[2]

6

In [20]:
arr=np.array([[1,2,3],[5,6,7]])
print(arr[1,2])

7


In [21]:
arr[1,2]=999
arr

array([[  1,   2,   3],
       [  5,   6, 999]])

# Numpy Slicing

In [22]:
arr=np.arange(11)
print(arr)
print(arr[::2])
print(arr[1:4])
print(arr[0:-4])

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]
[1 2 3]
[0 1 2 3 4 5 6]


In [23]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)
print(arr[:2,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[2 3]
 [7 8]]


In [24]:
print(arr[0:2,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
print(arr)
print(arr[2,1])#arr[r,c]
print(arr[[0,1,2],[0,1,0]])#arr[[r1,r2,r3],[c1,c2,c3]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
12
[ 1  7 11]


# Numpy Maths

In [32]:
#element wise operation
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(y)
print('*'*40)
print(np.add(x,y))
print('*'*40)
print(np.subtract(x,y))
print('*'*40)
print(np.multiply(x,y))
print('*'*40)
print(np.divide(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
****************************************
[[ 6  8]
 [10 12]]
****************************************
[[-4 -4]
 [-4 -4]]
****************************************
[[ 5 12]
 [21 32]]
****************************************
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [34]:
#Matrix Multiplication
print(np.matmul(x,y))
#Dot product(both are same)
print('*'*40)
print(np.dot(x,y))

[[19 22]
 [43 50]]
****************************************
[[19 22]
 [43 50]]


In [37]:
print(x)
print('*'*40)
print(np.sum(x))
print('*'*40)
print(np.sum(x,axis=0)) # column wise addition
print('*'*40)
print(np.sum(x,axis=1)) #row wise Addition

[[1 2]
 [3 4]]
****************************************
10
****************************************
[4 6]
****************************************
[3 7]


In [38]:
print(np.max(x))#retun max element
print(np.min(x))#retun min element

4
1


In [41]:
print(x)
print('*'*40)
print(x.T) # transpose matrix

[[1 2]
 [3 4]]
****************************************
[[1 3]
 [2 4]]


In [42]:
#exponential function
print(np.exp(1))
print(np.exp(2))

2.718281828459045
7.38905609893065


# Numpy Statistics

In [49]:
height=np.array([186,156,289,156,231,189])

print(np.max(height))
print(np.min(height))
print(np.mean(height))
print(np.median(height))
#print(np.mode(height))
print(np.var(height))
print(np.std(height))

289
156
201.16666666666666
187.5
2177.138888888889
46.65982092645544


In [53]:
# Correlation Coefficient b/w height and weight
height=np.array([175, 163, 182, 168, 160, 178, 171, 185, 158, 176])
weight=np.array([68, 52, 79, 61, 55, 71, 66, 84, 49, 72])
print(np.corrcoef(height,weight))

[[1.         0.98382722]
 [0.98382722 1.        ]]


In [55]:
person=np.corrcoef(height,weight)

print(person[0,1])

0.9838272216674189
